import type { DispatchDeviations, DispatchDeviationSuggestion } from '../types'
import { formatNumber } from '../lib/utils'
import { Badge, Button, Card, CardContent, CardHeader, SectionTitle } from './ui'

export function DeviationBoard({ data, busy, showSuggestions, confirmedSuggestionIds, onConfirm }: { data?: DispatchDeviations | null; busy: boolean; showSuggestions: boolean; confirmedSuggestionIds: string[]; onConfirm: (suggestion: DispatchDeviationSuggestion) => void }) {
  if (!data?.has_deviations) return null
  const confirmed = new Set(confirmedSuggestionIds)
  return <Card aria-label="配送偏差與參數建議"><CardHeader><SectionTitle title="今日偏差紀錄" detail="由配送時間軸的可重現進度統計" /><Badge tone="warning">已記錄 {formatNumber(data.vehicle_deviations.length + data.zone_deviations.length)} 項</Badge></CardHeader><CardContent><div className="space-y-3">{data.vehicle_deviations.map((item) => <div key={item.vehicle_id} className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3"><p className="text-sm font-semibold text-amber-950">{item.message}</p><p className="mt-1 text-xs leading-5 text-amber-800">下次排班會調高這台車的行駛時間估計，或少排 2 站。</p></div>)}{data.zone_deviations.map((item) => <div key={item.zone_code} className="rounded-lg border border-blue-200 bg-blue-50 px-4 py-3"><p className="text-sm font-semibold text-blue-950">{item.message}</p><p className="mt-1 text-xs leading-5 text-blue-800">建議將 {item.zone_code} 的服務時間由 {item.baseline_service_minutes} 分鐘調整為 {item.suggested_service_minutes} 分鐘。</p></div>)}</div>{showSuggestions && data.suggestions.map((suggestion) => { const isConfirmed = confirmed.has(suggestion.suggestion_id); return <div key={suggestion.suggestion_id} className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-200 bg-white px-4 py-3"><div><p className="text-sm font-semibold text-slate-900">參數修正建議</p><p className="mt-1 text-xs text-slate-600">{suggestion.message}</p></div><Button type="button" variant="secondary" disabled={busy || isConfirmed} onClick={() => onConfirm(suggestion)}>{isConfirmed ? '已確認，重新排班後生效' : `確認套用 ${suggestion.zone_code} ${suggestion.to_service_minutes} 分鐘`}</Button></div> })}</CardContent></Card>
}
