import type { Plan } from '../types'
import { formatDistance, formatDuration, formatWeight, vehicleLabel, cn } from '../lib/utils'
import { Badge, Card, CardContent, CardHeader, ProgressBar, SectionTitle } from './ui'

const zoneLabels: Record<string, string> = { Z1: '北區', Z2: '東區', Z3: '中區', Z4: '西區', Z5: '南區' }

export function VehicleBoard({ plan, activeVehicle, onSelectVehicle }: { plan: Plan; activeVehicle: string | null; onSelectVehicle: (id: string | null) => void }) {
  return <Card aria-label="車輛概況"><CardHeader><SectionTitle title="車輛概況" detail="每台車的任務、載重與路程" /><Badge tone="info">{plan.vehicles.length} 台車</Badge></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{plan.vehicles.map((vehicle) => <button type="button" key={vehicle.vehicle_id} className={cn('rounded-xl border border-slate-200 p-4 text-left transition hover:border-blue-300 hover:shadow-sm', activeVehicle === vehicle.vehicle_id && 'border-blue-500 bg-blue-50/60 ring-2 ring-blue-100')} onClick={() => onSelectVehicle(activeVehicle === vehicle.vehicle_id ? null : vehicle.vehicle_id)}><div className="flex items-center justify-between"><strong className="text-sm text-slate-900">{vehicleLabel(vehicle.vehicle_id)}</strong><span className="text-xs font-semibold text-slate-500">{Math.round(vehicle.load_utilization * 100)}%</span></div><p className="mt-1 text-xs text-slate-500">{vehicle.vehicle_name} · {vehicle.order_count} 張訂單</p><div className="mt-3"><ProgressBar value={vehicle.load_utilization} tone={vehicle.load_utilization > 0.9 ? 'amber' : 'green'} /></div><div className="mt-3 grid grid-cols-2 gap-x-3 gap-y-1.5 text-xs"><span className="flex items-baseline justify-between gap-2 whitespace-nowrap"><span className="text-slate-500">{'載重 '}</span><strong className="font-bold tabular-nums text-slate-900">{formatWeight(vehicle.planned_load_kg)}</strong></span><span className="flex items-baseline justify-between gap-2 whitespace-nowrap"><span className="text-slate-500">{'上限 '}</span><strong className="font-bold tabular-nums text-slate-900">{formatWeight(vehicle.max_load_kg)}</strong></span><span className="flex items-baseline justify-between gap-2 whitespace-nowrap"><span className="text-slate-500">{'路程 '}</span><strong className="font-bold tabular-nums text-slate-900">{formatDistance(vehicle.total_distance_m)}</strong></span><span className="flex items-baseline justify-between gap-2 whitespace-nowrap"><span className="text-slate-500">{'時間 '}</span><strong className="font-bold tabular-nums text-slate-900">{formatDuration(vehicle.total_duration_s)}</strong></span></div><p className="mt-3 text-xs font-medium text-blue-700">服務區域：{vehicle.service_zone_codes.map((code) => zoneLabels[code] ? `${zoneLabels[code]}（${code}）` : code).join('、') || '未指定'}</p></button>)}</CardContent></Card>
}
