import { expect, test } from '@playwright/test'
import path from 'node:path'

const workbook = path.resolve('..', 'data', 'samples', 'demo-50-tight.xlsx')
const shots = path.resolve('..', 'docs', 'screenshots')

test('boxellent 工作區：地圖常駐，明細按需展開，發車後時間軸在明細內', async ({ page }) => {
  test.setTimeout(300_000)
  const consoleErrors: string[] = []
  const forbiddenRequests: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('request', (request) => { const url = request.url(); if (url.includes('googleapis') || url.endsWith('/dispatch')) forbiddenRequests.push(url) })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await expect(page.getByText('boxellent', { exact: true })).toBeVisible()
  await page.screenshot({ path: path.join(shots, 'BOX-01-empty.png') })

  await page.getByLabel('上傳 Excel').setInputFiles(workbook)
  await page.getByRole('button', { name: '送出', exact: true }).click()
  await expect(page.locator('.topbar-stats')).toContainText('49/50', { timeout: 240_000 })
  await expect(page.getByLabel('配送地圖', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '查看明細' })).toBeVisible()
  const mapBox = await page.locator('.stage-map').boundingBox()
  const chatBox = await page.locator('.stage-chat').boundingBox()
  const zoomBox = await page.locator('.leaflet-control-zoom').boundingBox()
  const closedDetailBox = await page.locator('.detail-closed').boundingBox()
  expect(mapBox && chatBox && zoomBox && closedDetailBox).toBeTruthy()
  if (mapBox && chatBox && zoomBox && closedDetailBox) {
    expect(chatBox.x - mapBox.x).toBeGreaterThanOrEqual(6)
    expect(chatBox.x - mapBox.x).toBeLessThanOrEqual(16)
    expect(zoomBox.x).toBeGreaterThan(mapBox.x + mapBox.width - 90)
    expect(Math.abs(mapBox.y + mapBox.height - chatBox.y - chatBox.height)).toBeLessThanOrEqual(12)
    expect(closedDetailBox.width).toBeLessThanOrEqual(150)
  }
  await page.waitForTimeout(2500)
  await page.screenshot({ path: path.join(shots, 'BOX-02-map.png') })
  const pageScroll = await page.evaluate(() => document.documentElement.scrollHeight - window.innerHeight)
  expect(pageScroll).toBeLessThanOrEqual(2)

  await page.getByRole('button', { name: '查看明細' }).click()
  await expect(page.getByRole('list', { name: '四台車訂單看板' })).toBeVisible()
  const firstOrder = page.locator('.order-board-stop').first()
  await firstOrder.locator('.order-board-order').click()
  await expect(page.getByRole('button', { name: '調整車輛或站序' })).toHaveCount(0)
  const clippedOrderIds = await page.locator('.order-board-stop .obs-id').evaluateAll((nodes) => nodes.filter((node) => node.scrollWidth > node.clientWidth + 1).length)
  expect(clippedOrderIds).toBe(0)
  await page.waitForTimeout(350)
  await page.screenshot({ path: path.join(shots, 'BOX-03-orders.png') })
  await page.locator('.detail-inner').evaluate((node) => { node.scrollTop = node.scrollHeight })
  await page.getByRole('button', { name: '收起明細' }).click()
  await page.getByRole('button', { name: '開始裝車' }).click()
  await expect(page.locator('.stage-loaded')).toBeVisible()
  await expect(page.locator('.feedback-success')).toContainText('已開始裝車')
  await expect(page.locator('.feedback-success')).toHaveCount(0, { timeout: 7000 })
  await page.getByRole('button', { name: '模擬出發' }).click()
  await expect(page.getByRole('slider', { name: '配送時間軸' })).toBeVisible()
  await expect.poll(() => page.locator('.detail-inner').evaluate((node) => node.scrollTop)).toBe(0)
  await page.waitForTimeout(350)
  await page.screenshot({ path: path.join(shots, 'BOX-04-timeline.png') })
  const slider = page.getByRole('slider', { name: '配送時間軸' })
  await slider.fill((await slider.getAttribute('max')) || '660')
  await expect(page.locator('.timeline-end')).toContainText('今日模擬行程已跑完', { timeout: 30_000 })
  await expect(page.getByRole('button', { name: '查看今日回顧' })).toBeInViewport()
  await page.screenshot({ path: path.join(shots, 'BOX-04-end.png') })
  await page.getByRole('button', { name: '查看今日回顧' }).click()
  await expect(page.getByLabel('今日回顧位置')).toBeVisible()
  await page.waitForTimeout(350)
  await page.screenshot({ path: path.join(shots, 'BOX-05-review.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.waitForTimeout(350)
  const detailWidth = await page.locator('.detail-drawer').evaluate((node) => node.getBoundingClientRect().width)
  expect(detailWidth).toBeGreaterThan(300)
  await expect(page.getByRole('button', { name: '收起明細' })).toBeVisible()
  const noteClipped = await page.locator('.stage-note').evaluate((node) => node.scrollWidth > node.clientWidth || node.scrollHeight > node.clientHeight)
  expect(noteClipped).toBe(false)
  for (const selector of ['.topbar-more summary', '.map-route-filter', '.detail-tabs button', '.detail-expand']) {
    const height = await page.locator(selector).first().evaluate((node) => node.getBoundingClientRect().height)
    expect(height).toBeGreaterThanOrEqual(44)
  }
  await page.screenshot({ path: path.join(shots, 'BOX-06-mobile.png'), fullPage: true })
  const horizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
  expect(horizontalOverflow).toBeLessThanOrEqual(2)
  expect(consoleErrors).toEqual([])
  expect(forbiddenRequests).toEqual([])
})

test('等待 Agent 時有呼吸燈，取得回覆後顯示實際工具', async ({ page }) => {
  await page.route('**/api/v1/agent/chat', async (route) => {
    await new Promise((resolve) => setTimeout(resolve, 1200))
    await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ session_id: 'test-session', agent_run_id: 'test-run', message: '已查詢方案。', evidence: [{ tool: 'inspect_plan_overview', data: {} }], requires_human_confirmation: false }) })
  })
  await page.goto('/')
  const input = page.getByRole('textbox', { name: '輸入訊息' })
  await input.fill('目前方案如何')
  await input.press('Enter')
  await expect(page.locator('.chat-thinking-status')).toContainText('正在理解需求並選擇工具')
  await expect(page.locator('.chat-breathing-light')).toHaveCSS('animation-name', 'boxellent-breathe')
  await page.screenshot({ path: path.join(shots, 'BOX-07-thinking.png') })
  await expect(page.locator('.chat-activity-skill').last()).toContainText('inspect_plan_overview')
  await expect(page.locator('.chat-thinking-status')).toHaveCount(0)
})
