import { expect, test } from '@playwright/test'
import path from 'node:path'

const workbook = path.resolve('..', 'data', 'samples', 'demo-50-tight.xlsx')
const shots = path.resolve('..', 'docs', 'screenshots')

test('Demo 工作區：開場、排班、放大看板、三階段', async ({ page }) => {
  test.setTimeout(300_000)
  const consoleErrors: string[] = []
  const forbiddenRequests: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('request', (request) => {
    const url = request.url()
    if (url.includes('googleapis') || url.endsWith('/dispatch')) forbiddenRequests.push(url)
  })

  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '配送調度控制塔' })).toBeVisible()
  await expect(page.getByText('先放入今天的訂單')).toBeVisible()
  await page.screenshot({ path: path.join(shots, 'UX2-01-empty.png') })

  await page.getByLabel('上傳 Excel').setInputFiles(workbook)
  await page.getByRole('button', { name: '送出', exact: true }).click()
  await expect(page.locator('.topbar-stats')).toContainText('49/50', { timeout: 240_000 })
  await expect(page.getByLabel('配送地圖', { exact: true })).toBeVisible()
  const chat = await page.locator('.stage-chat').boundingBox()
  const map = await page.locator('.stage-map').boundingBox()
  const detail = await page.locator('.detail-drawer').boundingBox()
  expect(chat && map && detail).toBeTruthy()
  expect(chat!.x).toBeGreaterThan(map!.x)
  expect(chat!.x + chat!.width).toBeLessThan(map!.x + map!.width)
  expect(chat!.y).toBeGreaterThan(map!.y)
  expect(chat!.y + chat!.height).toBeLessThan(map!.y + map!.height)
  expect(map!.y + map!.height).toBeLessThanOrEqual(detail!.y)
  await page.waitForTimeout(1000)
  await page.screenshot({ path: path.join(shots, 'UX3-02-overview.png') })

  await page.getByRole('button', { name: '放大訂單看板' }).click()
  await expect(page.getByRole('button', { name: '顯示完整地圖' })).toBeVisible()
  const compactMap = await page.locator('.stage-map').boundingBox()
  expect(compactMap!.height).toBeLessThan(map!.height)
  await page.screenshot({ path: path.join(shots, 'UX2-03-board.png') })

  await page.getByRole('button', { name: '顯示完整地圖' }).click()
  await page.getByRole('button', { name: '開始裝車' }).click()
  await expect(page.locator('.app-shell.stage-loaded')).toBeVisible()
  await page.screenshot({ path: path.join(shots, 'UX2-04-loaded.png') })
  await page.getByRole('button', { name: '模擬出發' }).click()
  await expect(page.locator('.app-shell.stage-dispatched')).toBeVisible()
  await expect(page.locator('#dispatch-timeline')).toBeVisible()
  const slider = page.getByRole('slider', { name: '配送時間軸' })
  await slider.fill((await slider.getAttribute('max')) || '660')
  await expect(page.getByText('今日模擬行程已跑完')).toBeVisible({ timeout: 30_000 })
  await expect(page.locator('.day-complete-pill')).toContainText('今日模擬行程結束')
  await expect(page.locator('.timeline-end')).toContainText('並非實際簽收')
  await page.getByRole('button', { name: '查看今日回顧' }).click()
  await expect(page.getByLabel('今日回顧位置')).toBeFocused()
  await page.screenshot({ path: path.join(shots, 'UX3-05-review-navigation.png') })

  expect(consoleErrors).toEqual([])
  expect(forbiddenRequests).toEqual([])
})

test('窄螢幕仍能讀取開場與排班資訊', async ({ page }) => {
  test.setTimeout(240_000)
  await page.setViewportSize({ width: 768, height: 900 })
  await page.goto('/')
  await expect(page.getByText('先放入今天的訂單')).toBeVisible()
  await page.screenshot({ path: path.join(shots, 'UX2-06-empty-narrow.png') })
  await page.getByLabel('上傳 Excel').setInputFiles(workbook)
  await page.getByRole('button', { name: '送出', exact: true }).click()
  await expect(page.locator('.topbar-stats')).toContainText('49/50', { timeout: 240_000 })
  await expect(page.getByLabel('配送地圖', { exact: true })).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
  const overflowSources = await page.evaluate(() => [...document.querySelectorAll('*')].filter((element) => element.getBoundingClientRect().right > window.innerWidth + 2).slice(0, 8).map((element) => `${element.tagName}.${element.className}: ${Math.round(element.getBoundingClientRect().right)}`))
  expect(overflow, overflowSources.join(' | ')).toBeLessThanOrEqual(2)
  await expect.poll(() => page.locator('.stage-chat .chat-log').evaluate((log) => log.scrollTop)).toBe(0)
  await page.waitForTimeout(2500)
  await page.screenshot({ path: path.join(shots, 'UX2-07-overview-narrow.png'), fullPage: true })
})

test('手機寬度可上傳並讀取方案', async ({ page }) => {
  test.setTimeout(240_000)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByText('先放入今天的訂單')).toBeVisible()
  await page.getByLabel('上傳 Excel').setInputFiles(workbook)
  await page.getByRole('button', { name: '送出', exact: true }).click()
  await expect(page.locator('.topbar-stats')).toContainText('49/50', { timeout: 240_000 })
  await expect(page.getByLabel('配送地圖', { exact: true })).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
  const overflowSources = await page.evaluate(() => [...document.querySelectorAll('*')].filter((element) => element.getBoundingClientRect().right > window.innerWidth + 2).slice(0, 8).map((element) => `${element.tagName}.${element.className}: ${Math.round(element.getBoundingClientRect().right)}`))
  expect(overflow, overflowSources.join(' | ')).toBeLessThanOrEqual(2)
  await expect.poll(() => page.locator('.stage-chat .chat-log').evaluate((log) => log.scrollTop)).toBe(0)
  await page.waitForTimeout(2500)
  await page.screenshot({ path: path.join(shots, 'UX2-08-overview-phone.png'), fullPage: true })
  await page.getByRole('button', { name: '查看明細' }).click()
  const sourceOrderId = await page.locator('.order-board-order .obs-id').first().innerText()
  await page.locator('.order-board-order').first().click()
  await page.getByRole('button', { name: '用表單調整' }).click()
  await page.getByLabel(`${sourceOrderId} 目標車輛`).selectOption('VEH-002')
  await page.locator('.board-move-controls').first().screenshot({ path: path.join(shots, 'UX2-09-phone-adjust-controls.png') })
  await page.getByRole('button', { name: '試算調整' }).click()
  await expect(page.getByLabel('跨車站序預覽結果')).toBeVisible({ timeout: 30_000 })
  await page.getByLabel('跨車站序預覽結果').screenshot({ path: path.join(shots, 'UX2-10-phone-adjust-result.png') })
})

test('地圖疊放對話後，仍可拖曳訂單跨車試算', async ({ page }) => {
  test.setTimeout(240_000)
  const consoleErrors: string[] = []
  const forbiddenRequests: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('request', (request) => { const url = request.url(); if (url.includes('googleapis') || url.endsWith('/dispatch')) forbiddenRequests.push(url) })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await page.getByLabel('上傳 Excel').setInputFiles(workbook)
  await page.getByRole('button', { name: '送出', exact: true }).click()
  await expect(page.locator('.topbar-stats')).toContainText('49/50', { timeout: 240_000 })
  const board = page.getByRole('list', { name: '四台車訂單看板' })
  const target = page.getByRole('region', { name: 'VEH-004 訂單欄' }).locator('.order-board-stop').nth(4)
  await board.locator('[data-order-id="ORD-042"]').dragTo(target)
  await expect(page.getByLabel('跨車站序預覽結果')).toBeVisible({ timeout: 30_000 })
  await page.screenshot({ path: path.join(shots, 'UX3-06-drag-preview.png') })
  await page.getByLabel('跨車站序預覽結果').getByRole('button', { name: '套用變更' }).click()
  await expect(page.getByRole('region', { name: 'VEH-004 訂單欄' }).locator('[data-order-id="ORD-042"]')).toHaveClass(/order-board-stop-changed/, { timeout: 60_000 })
  await expect(page.locator('.map-change-summary')).toContainText('ORD-042')
  await expect(page.locator('.map-stop-changed')).toHaveCount(1)
  await page.locator('.stage-map').scrollIntoViewIfNeeded()
  await page.screenshot({ path: path.join(shots, 'UX3-07-map-change-summary.png') })
  await page.getByRole('button', { name: '查看變更' }).click()
  await expect(page.getByRole('region', { name: 'VEH-004 訂單欄' }).locator('[data-order-id="ORD-042"]')).toBeInViewport({ ratio: 0.5 })
  await page.screenshot({ path: path.join(shots, 'UX3-07-cross-vehicle-highlight.png') })
  expect(consoleErrors).toEqual([])
  expect(forbiddenRequests).toEqual([])
})
